[phases.setup]
nixPkgs = ["...", "nodejs", "yarn"]

[phases.install]
cmds = ["echo INSTALLING", "WORKDIR backend/", "npm i", "WORKDIR client/", "npm i"]

[phases.build]
builder = "NIXPACKS"
cmds = ["echo BUILDING", "WORKDIR backend/", "npm run build/"]

[deploy]
cmds = ["cd backend/ && npm run prod"]