[phases.setup]
nixPkgs = ['nodejs, 'yarn']

[phases.install]
cmds = ["WORKDIR /backend", "npm i" "WORKDIR /client", "npm i"]

[phases.build]
cmds = ["WORKDIR /backend", "npm run build"]

[deploy]
cmds = ["cd /backend && npm run prod"]